language: node_js
before_script:
  - npm install -g mocha
  - npm install mocha
node_js:
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8